In [2]:
import nashpy as nash
import numpy as np
A=np.array([[2,0],[4,2]]) # A is the row player
B= np.array([[4,2],[2,0]]) # B is the column player
game1=nash.Game(A,B)
game1

Bi matrix game with payoff matrices:

Row player:
[[2 0]
 [4 2]]

Column player:
[[4 2]
 [2 0]]

In [3]:
equilibria = game1.support_enumeration()
for eq in equilibria:
    print(eq)

(array([0., 1.]), array([1., 0.]))


In [4]:
A = np.array([[4,0],[0,2]]) # A is the row player
B = np.array([[2,0],[0,4]]) # B is the column player
game2 = nash.Game(A,B)
game2

Bi matrix game with payoff matrices:

Row player:
[[4 0]
 [0 2]]

Column player:
[[2 0]
 [0 4]]

In [5]:
equilibria = game2.support_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0.]), array([1., 0.]))
(array([0., 1.]), array([0., 1.]))
(array([0.66666667, 0.33333333]), array([0.33333333, 0.66666667]))


In [6]:
sigma_r = np.array([.67,.33])
sigma_c = np.array([.33,.67])
pd = nash.Game(A, B)
pd[sigma_r, sigma_c]

array([1.3266, 1.3266])